[package]
name = "puddin-python"
version = "0.1.0"
edition = "2021"
authors = []
license = "MIT OR Apache-2.0"

[lib]
name = "puddin"
crate-type = ["cdylib"]

[dependencies]
puddin = { path = "../../crates/puddin" }
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"

[workspace]
